In [9]:
#엠베딩 - 컴퓨터가 알 수 있게 값을 변환. 
import pandas as pd
class2 = pd.read_csv('./data/class2.csv')
print(class2)

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

train_x = label_encoder.fit_transform(class2['class2'])
train_x

   Unnamed: 0      id tissue class class2      x      y      r
0           0  mdb000      C  CIRC      N  535.0  475.0  192.0
1           1  mdb001      A  CIRA      N  433.0  268.0   58.0
2           2  mdb002      A  CIRA      I    NaN    NaN    NaN
3           3  mdb003      C  CIRC      B    NaN    NaN    NaN
4           4  mdb004      F  CIRF      I  488.0  145.0   29.0
5           5  mdb005      F  CIRF      B  544.0  178.0   26.0


array([2, 2, 1, 0, 1, 0])

In [10]:
# 횟수 기반 임베딩(CounterVectorizer())
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is last chance.',
    'and if you do not have this chance.',
    'you will never get any chance.',
    'will you do get this one?',
    'please, get this chance',
]
vect = CountVectorizer()   # 객체 생성
vect.fit(corpus)   # 모델 동작
vect.vocabulary_   # 결과 확인

{'this': 13,
 'is': 7,
 'last': 8,
 'chance': 2,
 'and': 0,
 'if': 6,
 'you': 15,
 'do': 3,
 'not': 10,
 'have': 5,
 'will': 14,
 'never': 9,
 'get': 4,
 'any': 1,
 'one': 11,
 'please': 12}

In [11]:
# 'you will never get any chance.' 를 변형 처리 한 결과를 배열로... 
vect.transform(['you will never get any chance.']).toarray()

array([[0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [12]:
# 불용어 제거 및 카운터 벡터 확인
# stop_words 옵션에 불용어를 지정하여 제외... 
vect = CountVectorizer(stop_words=['and', 'is','please','this']).fit(corpus)
vect.vocabulary_

{'last': 6,
 'chance': 1,
 'if': 5,
 'you': 11,
 'do': 2,
 'not': 8,
 'have': 4,
 'will': 10,
 'never': 7,
 'get': 3,
 'any': 0,
 'one': 9}

In [13]:
# 'you will never get any chance.' 를 변형 처리 한 결과를 배열로... 
vect.transform(['you will never get any chance.']).toarray()

array([[1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1]], dtype=int64)

In [14]:
# TF-IDF
# TF - 문서내에 특정 단어의 출현 빈도
# IDF - 특정 단어가 전체 문서 중 출현한 빈도를 Inverse한 내용
# 사용하는 상황
# 키워드 검색을 기반으로 하는 검색 엔진
# 중요 키워드 분석
# 검색 엔진에서 검색 결과의 순위를 결정
# TfidfVectorizer()

from sklearn.feature_extraction.text import TfidfVectorizer
doc = ['I like machine learning','I love deep learning','I run everyday']
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(doc)
doc_distance = (tfidf_matrix * tfidf_matrix.T)
print("유사도를 위한 ", str(doc_distance.get_shape()[0]), 'x',str(doc_distance.get_shape()[1]), 
    '행렬을 만들었습니다.')
print(doc_distance.toarray())

유사도를 위한  3 x 3 행렬을 만들었습니다.
[[1.       0.224325 0.      ]
 [0.224325 1.       0.      ]
 [0.       0.       1.      ]]


In [15]:
# 예측 기반 임베딩
# 신경망 구조 혹은 모델을 이용하여 특정 문맥에서 어떤 단어가 나올지 예측하면서 단어를 벡터로 만드는 방식
# Word2Vector가 있음(gensim).

# Word2Vec

from nltk.tokenize import sent_tokenize, word_tokenize
import warnings
warnings.filterwarnings(action='ignore')  # 경고 무시... 
import gensim
from gensim.models import Word2Vec

# 샘플 데이터로 peter.txt(피터팬)
sample = open('./data/peter.txt', 'r',encoding='utf8')
s = sample.read()

f = s.replace("\n", " ")  # 줄바꿈을 공백으로 변환
data = []

for i in sent_tokenize(f): # 로딩한 파일의 각 문장마다 반복(문장 토큰화)
    temp = []
    for j in word_tokenize(i):   # 문장을 단어로 토큰화
        temp.append(j.lower())   # 토큰화된 단어를 소문자로 변환하여 temp에 저장
    data.append(temp)
data

[['once',
  'upon',
  'a',
  'time',
  'in',
  'london',
  ',',
  'the',
  'darlings',
  'went',
  'out',
  'to',
  'a',
  'dinner',
  'party',
  'leaving',
  'their',
  'three',
  'children',
  'wendy',
  ',',
  'jhon',
  ',',
  'and',
  'michael',
  'at',
  'home',
  '.'],
 ['after',
  'wendy',
  'had',
  'tucked',
  'her',
  'younger',
  'brothers',
  'jhon',
  'and',
  'michael',
  'to',
  'bed',
  ',',
  'she',
  'went',
  'to',
  'read',
  'a',
  'book',
  '.'],
 ['she', 'heard', 'a', 'boy', 'sobbing', 'outside', 'her', 'window', '.'],
 ['he', 'was', 'flying', '.'],
 ['there', 'was', 'little', 'fairy', 'fluttering', 'around', 'him', '.'],
 ['wendy', 'opened', 'the', 'window', 'to', 'talk', 'to', 'him', '.'],
 ['“', 'hello', '!'],
 ['who', 'are', 'you', '?'],
 ['why', 'are', 'you', 'crying', '”', ',', 'wendy', 'asked', 'him', '.'],
 ['“', 'my', 'name', 'is', 'peter', 'pan', '.'],
 ['my',
  'shadow',
  'wouldn',
  '’',
  't',
  'stock',
  'to',
  'me.',
  '”',
  ',',
  'he',
  'rep

In [16]:
#CBOW(Continuous Bag Of Words)
# 단어를 여러개 나열한 후 이와 관련된 단어를 추정하는 방식
model1 = Word2Vec(data, min_count=1, vector_size=100, window=5, sg=0)  # sg값이 0인 경우, CBOW
print("Cosine similarity between 'peter', 'wendy' - CBOW : ",
      model1.wv.similarity('peter','wendy'))   # 책에 있는 함수와 유사한 동작하는 함수

Cosine similarity between 'peter', 'wendy' - CBOW :  0.07439383


In [17]:
print("Cosine similarity between 'peter', 'hook' - CBOW : ",
      model1.wv.similarity('peter','hook'))

Cosine similarity between 'peter', 'hook' - CBOW :  0.027709864


In [18]:
#skip-gram
# CBOW방식과 반대로 특정한 단어에서 문맥이 될 수 있는 단어를 예측
model2 = Word2Vec(data, min_count=1, vector_size=100, window=5, sg=1)  # sg값이 1인 경우, skip-gram
print("Cosine similarity between 'peter', 'wendy' - skip Gram : ",
      model2.wv.similarity('peter','wendy'))   # 책에 있는 함수와 유사한 동작하는 함수

Cosine similarity between 'peter', 'wendy' - skip Gram :  0.40088683


In [19]:
print("Cosine similarity between 'peter', 'hook' - skip Gram : ",
      model2.wv.similarity('peter','hook'))

Cosine similarity between 'peter', 'hook' - skip Gram :  0.52016735


In [20]:
# 예측기반 임베딩

# 패스트 텍스트(FastText)
# 워드투벡터의 단점을 보완하고자 페이스북에서 개발한 임베딩 알고리즘
# 워드투벡터는 워드 엠베딩 방식이 분산 표현을 이용하여 단어의 분산 분포가 유사한 단어들에 비슷한 벡터 값을 할당
# 하여 표현하는 방식
# 워드투벡터는 사전에 없는 단어에 대해서는 벡터 값을 얻을 수 없음.(*워드투벡터의 단점)
# 자주 사용되지 않는 단어에 대해서는 학습이 불안정
# 패스트텍스트는 이 단점을 보완하기 위해서 개발된 단어 표현 방식을 사용. 
# 패스트텍스트는 노이즈에 강하며, 새로운 단어에 대해서는 형태적 유사성을 고려한 벡터 값을 얻기 때문에
# 자연어 처리 분야에서 많이 사용되고 있음. 

In [25]:
# 패스트텍스트
from gensim.test.utils import common_texts
from gensim.models import FastText

model = FastText('.data/peter.txt', vector_size=100, window=5, min_count=5, workers=4, sg=1)

RuntimeError: you must first build vocabulary before training the model

In [ ]:
# peter, wendy의 유사도
sim_score = model.wv.similarity('peter', 'wendy')
print(sim_score)

In [7]:
# peter, hook의 유사도
sim_score = model.wv.similarity('peter', 'hook')
print(sim_score)

NameError: name 'model' is not defined

In [ ]:
# 패스트텍스트 훈련된 모델을 이용한 작업
# https://fasttext.cc/docs/en/pretrained-vectors.html 에서 언어에 맞는 모델 다운로드

from __future__ import print_function
from gensim.models import KeyedVectors

# 모델 로딩
model_kr = KeyedVectors.load_word2vec_format('./data/wiki.ko.vec')

In [30]:
# 사전 훈련된 모델을 이용한 유사도 확인

find_similar_to = '노력'

for similar_word in model_kr.similar_by_word(find_similar_to):
    print("단어 : {0}, 유사도 : {1}".format(similar_word[0], similar_word[1]))

단어 : 노력함, 유사도 : 0.7967213988304138
단어 : 노력중, 유사도 : 0.7502310276031494
단어 : 노력만, 유사도 : 0.7195296883583069
단어 : 노력과, 유사도 : 0.7137251496315002
단어 : 노력의, 유사도 : 0.6944872736930847
단어 : 노력가, 유사도 : 0.6931817531585693
단어 : 노력이나, 유사도 : 0.685508668422699
단어 : 노력없이, 유사도 : 0.6761217713356018
단어 : 노력맨, 유사도 : 0.6756712198257446
단어 : 노력보다는, 유사도 : 0.6753138303756714


In [29]:
similarities = model_kr.most_similar(positive=['동물', '육식동물'], negative=['사람'])
for sim in similarities:
    print(sim)

('초식동물', 0.7804121971130371)
('거대동물', 0.7547271251678467)
('육식동물의', 0.7547166347503662)
('유두동물', 0.753511369228363)
('반추동물', 0.7470759749412537)
('독동물', 0.7466291189193726)
('육상동물', 0.7460315823554993)
('유즐동물', 0.7450903654098511)
('극피동물', 0.7449345588684082)
('복모동물', 0.7424345016479492)


In [32]:
# 글로브(GloVe : Global Vectors for Word Representation)
# 횟수 기반과 예측기반의 단점을 보완하기 위한 임베딩 기법

import numpy as np
%matplotlib notebook
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from sklearn.decomposition import PCA
from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec

# GloVe 다운로드
glove_file = datapath('d:/kim/TENSORFLOW/data/glove.6B.100d.txt')   
word2vec_glove_file = get_tmpfile("glove.6B.100d.word2vec.txt")
glove2word2vec(glove_file, word2vec_glove_file)

(400000, 100)

In [34]:
# bill 관련 단어와 유사한 단어 리스트 보기
model = KeyedVectors.load_word2vec_format(word2vec_glove_file)
model.most_similar('bill')

[('legislation', 0.8072139620780945),
 ('proposal', 0.7306863069534302),
 ('senate', 0.7142541408538818),
 ('bills', 0.704440176486969),
 ('measure', 0.6958034634590149),
 ('passed', 0.690624475479126),
 ('amendment', 0.6846878528594971),
 ('provision', 0.684556782245636),
 ('plan', 0.6816463470458984),
 ('clinton', 0.6663140058517456)]

In [38]:
model.most_similar(negative='cherry')

[('kazushige', 0.4834350645542145),
 ('askerov', 0.4778185784816742),
 ('lakpa', 0.4691525399684906),
 ('ex-gay', 0.45713329315185547),
 ('tadayoshi', 0.4522107243537903),
 ('turani', 0.44810065627098083),
 ('saglam', 0.446959912776947),
 ('aijun', 0.443526953458786),
 ('adjustors', 0.44235292077064514),
 ('nyum', 0.4423118233680725)]

In [39]:
result = model.most_similar(positive=['woman', 'king'], negative=['man'])
print("{}: {:.4f}".format(*result[0]))
        # └단어, 유사도 순으로 출력됨

queen: 0.7699


In [41]:
def analogy(x1, x2, y1):
    result = model.most_similar(positive=[y1, x2], negative=[x1])
    return result[0][0]
analogy('australia', 'beer', 'france')

'champagne'

In [42]:
def analogy(x1, x2, y1):
    result = model.most_similar(positive=[y1, x2], negative=[x1])
    return result[0][0]
analogy('tall', 'tallest', 'long')

'longest'

In [43]:
# 열거된 단어 중 유사성이 가장 떨어지는 단어 반환하는 코드
model.doesnt_match("breakfast cereal dinner lunch".split())     # doesnt_match() 함수는 열거된 단어 중 유사성이 가장 떨어지는 단어를 반환

'cereal'